### ISSUE TITLE
Identify realm officers.

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-project#11]
Identify realm officers (from w/in ES-DOC) to create specializations & then work w/ scientists - by showing them mindmaps - to complete those specializations.

@eguil  estimates completion of all realms by December.  Both @allynt & Mark Elkington require a significant amount of these to be complete prior to end-user testing.

**Comment by allynt** [comment]
Realm Officers need to understand that changes to specializations are **frowned upon**, and deletions of properties or enumerations in specializations are **not allowed**.

**Comment by eguil** [comment]
For now we have (following realm names in https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_realm.json):

- "ocnBgchem: Eric G.
- "aerosol", Charlotte P.
- "atmos", Charlotte P.
- "atmosChem", Charlotte P.
- "land", tbd (via Eric G.)
- "landIce", tbd
- "ocean", Eric G.
- "ocnBgchem", Eric G.
- "seaIce", Ruth P.
