### ISSUE TITLE
Add cdf2cim documentation to wordpress site

### ISSUE THREAD

**Issue by esdoc-system-user** [ES-DOC/esdoc-project#51]
Docs currently in cdf2cim repo at https://github.com/ES-DOC/esdoc-cdf2cim/blob/master/ESG_Publisher_Integration.pdf. Should also link from wordpress site

**Comment by eguil** [comment]
This is a doc for ESGF team

**Comment by davidhassell** [comment]
Check to see if we can put responsible parties into Ensemble documents
