### ISSUE TITLE
Review CIM2 simulation and ensemble classes

### ISSUE THREAD

**Issue by eguil** [ES-DOC/esdoc-project#61]
Review and propose changes according to procedure described in esdoc-cim-v2-schema repo in CONTRIBUTING.md

**Comment by eguil** [comment]
One change proposed and reviewed by group.

**Comment by davidhassell** [comment]
Check to see if we can put responsible parties into Ensemble documents

**Comment by davidhassell** [comment]
Thees two classes look ok to me, at present
