### ISSUE TITLE
Strategy for rolling specialization out changes to the groups

### ISSUE THREAD

**Issue by davidhassell** [ES-DOC/esdoc-project#64]
This issue replaces #53 and #57. The strategy currently lives in a google doc:

https://docs.google.com/document/d/1Gs-YgwpBXTDdtzF5czAW4f8N2kWrioVke06EiXTHNm0/edit#

which contains:
* Basic strategy for releasing new versions of the specializations
* Practicalities of applying specialization changes
* Communication and documentation

This document highlights, in red, where immediate action is required.

**Comment by davidhassell** [comment]
### Communication and documentation

* What has changed between specialization releases is determined by the entries in the specialization request spreadsheet (https://docs.google.com/spreadsheets/d/1h1UQEGEBBbmM0Xs3E6ZVbS-5f7Vdiq1tT7e6tUAI4Nw/edit#gid=1921196076)
* A document describing these changes must be be prepared for the ES-DOC website, and the liaisons notified. When notifying the liaisons, any required actions must be highlighted. Required actions could arise from:
  * A new enumeration option
  * An entirely new question
  * A clarification of an ambiguous question
  * Etc.

For the changes to be picked up by a group, the relevant spreadsheets **must** be pushed up to the institutional GitHub repository. How should this be managed? Should we invite the liaison to tell us when they are ready for the update? That could be the safest, but could create more work for us, but if an update for a group only takes a few minutes, probably OK?

**Comment by davidhassell** [comment]
Perhaps the way forward is to tell the liaison that we need to update  the spreadsheets (and why - link to summary of new questions on ES-DOC website) but we can only do this when ALL of the realm spreadsheets and up to date in the remote repos on GitHub. The Liaison will tell us when this is so.

If we keep a file in the repo that contains the current version of the specializations set, then we can easily check on progress.

**Comment by eguil** [comment]
Strategy agreed - David to write it up and put it on the es-doc web site

**Comment by davidhassell** [comment]
https://es-doc.org/procedure-for-implementing-updates-to-the-model-spreadsheets/

**Comment by davidhassell** [comment]
The procedure has been written up on web site: https://es-doc.org/procedure-for-implementing-updates-to-the-model-spreadsheets/
