### ISSUE TITLE
Register 4 new PMIP experiments

### ISSUE THREAD

**Issue by durack1** [ES-DOC/esdoc-project#83]
@charliepascoe 4 new PMIP experiments are currently in discussion at WCRP-CMIP/CMIP6_CVs#898.

Discussions are ongoing, however it is likely the registration will be completed later this week, early next week

Ping @taylor13 @davidhassell @martinjuckes @jypeter
Ref cmip6dr/Request#123

**Comment by durack1** [comment]
@charliepascoe please note there are now 316 registered experiments for CMIP6, see [CMIP6_experiment_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html)

**Comment by jypeter** [comment]
@charliepascoe let me know if I should provide extra information here, once @durack1 has fixed two copy/paste problems in the CV

**Comment by charliepascoe** [comment]
@jypeter I've added past1000-volc-cluster as an alias to the volc-cluster-mill experiment.

**Comment by charliepascoe** [comment]
Experiment info can be found at https://github.com/WCRP-CMIP/CMIP6_CVs/issues/898#issuecomment-613969369

**Comment by charliepascoe** [comment]
@jypeter Is the esm-past1000 experiment still called past1000-esm in the past1000 GMD paper?
We can make the connection with either an "alias" (where an experiment is known by a different name elsewhere) or a "previous_name" (where an experiment was once called something else) depending on whether past1000-esm is still in use or not.

**Comment by charliepascoe** [comment]
@jypeter past1000 has the following forcing descriptions in the ES-DOC database:

past1000 WMGHG 
past1000 astronomical parameters
pre-industrial ice sheets
pre-industrial land-sea mask
past1000 land use
past1000 solar variability
past1000 volcanic aerosols

For the -solaronly and -volconly experiments, should the rest of the forcings be set to a pre-industrial state?

**Comment by charliepascoe** [comment]
@jypeter 
Does the second half of the past2k experiment duplicate the past1000?
Does it need to?

**Comment by charliepascoe** [comment]
Waiting for input from PI before uploading for publishing

**Comment by jypeter** [comment]
@charliepascoe 

- Thanks for creating a _past1000-volc-cluster_ alias (the original name in the GMD paper) pointing to `past1000-volc-cluster` (the existing CMIP6 experiment_id) ! I did not know about this _aliasing_ feature
- I think we can use this feature a second time and also create a _past1000esm_ alias (NO DASH, the original name in the GMD paper) pointing to `esm-past1000` (the name recommended by Paul, in order to be consistent with other existing `esm-` experiment_ids). I don't think groups have already run this experiment, so we probably don't need to use _previous_name_
- I will ask Johann Jungclaus' advice (the PI) to check the list of documented forcings. Is there a web page that he can open to see how the existing forcings appear? I have tried to open https://view.es-doc.org/, but it seems to stay stuck on _Downloading documentation ... please wait_
- The second half of the _past2k_ experiment is a _past1000_ experiment. What do you mean by _Does it need to_?

**Comment by charliepascoe** [comment]
@jypeter 
* great, I'll use those aliases. 
* try https://documentation.es-doc.org/cmip6/experiments/past1000
* I noticed that the past2k experiment runs from 0 to 1850, and that from 850 to 1850 past2k is very similar to (if not the same) as the past1000.  I suspect my question is naive but why does past2k need to duplicate past1000?

**Comment by taylor13** [comment]
It seems to me if the second half of the past2k experiment is forced with the same forcing as the past1000 experiment, then in the data archive, the 2nd half should be stored with ``experiment_id="past1000"`` and its ``parent_experiment_id="past2k"``.  Of course those running *only* the past1000 experiment would have``experiment_id="past1000"`` and its ``parent_experiment_id="no parent"`` (according to the current CV).  

So the metadata would indicate that different initialization procedures were used for different past1000 experiments, but I think most users would just like to get *all* the simulations of the past1000, and not have to get some of them by downloading a part of past2k experiment.

Of course other folks interested only in the runs covering the full 2k period would then have to download the past2k data plus the past1000 data *for those models who had run the full 2000 years*.

Thoughts?

**Comment by charliepascoe** [comment]
Hi @jypeter,
I'm following up on the question of baseline forcings for the -solaronly and volconly experiments.
Did you get a response from Johann Jungclaus yet?

**Comment by charliepascoe** [comment]
Hi @jypeter 
I'm following up on the -solaronly and volconly forcing specifications.
Should the non-solar and non-volcanic forcings be set to pre-industrial conditions?
If I don't hear back from you I will assume that these other forcings should be pre-industrial.

**Comment by charliepascoe** [comment]
I specified pre-industrial conditions for the non-volcanic and non-solar forcings.
